[voice]
host = 'localhost'
port = 10500

recognition_th = 0.99
timeout = 5.0

[voice.activation]
words = ['へい寝落ち']
file = ''

[[voice.commands]]
words = ['オン', 'つけて']
file = 'on.sh'

[[voice.commands]]
words = ['オフ', 'けして']
file = 'off.sh'
